openapi: 3.0.1
info:
  title: ''
  description: ''
  version: 1.0.0
paths:
  /v3/app/worksheets/{worksheet_id}/rows/batch:
    patch:
      summary: 批量更新行记录
      deprecated: false
      description: 批量更新行记录
      tags:
      - V3-beta（AI 友好）/工作表行记录
      - 工作表行记录
      parameters:
      - name: worksheet_id
        in: path
        description: 工作表 ID
        required: true
        schema:
          type: string
      - name: HAP-Appkey
        in: header
        description: appkey
        required: false
        schema:
          type: string
      - name: HAP-Sign
        in: header
        description: 签名
        required: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                rowIds:
                  type: array
                  items:
                    type: string
                fields:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                        description: 字段 ID/别名
                      value:
                        description: ' 字段值'
                        oneOf:
                        - type: string
                        - type: integer
                        - type: boolean
                        - type: array
                        - type: object
                        - type: number
                        type: 'null'
                      type:
                        type: string
                        description: 'SingleSelect/MultipleSelect:1=不增量选项，2=允许增加选项，默认为1


                          Attachment:0=覆盖，1=新增，默认为 0

                          '
                    required:
                    - id
                    - value
                triggerWorkflow:
                  type: boolean
                  description: 是否触发工作流
                  default: true
              required:
              - fields
              - rowIds
              title: ''
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      failedRowIds:
                        type: array
                        items:
                          type: string
                      successfulRowIds:
                        type: array
                        items:
                          type: string
                    required:
                    - failedRowIds
                    - successfulRowIds
                  success:
                    type: boolean
                    description: 是否调用成功
                  error_code:
                    type: integer
                    description: 错误代码
                  error_msg:
                    type: string
                    description: 错误消息
                required:
                - data
                - success
          headers: {}
      security: []
components:
  schemas: {}
  securitySchemes:
    bearer:
      type: bearer
      scheme: bearer
servers:
- url: https://api.mingdao.com
  description: 正式环境
security:
- bearer: []
