openapi: 3.0.1
info:
  title: ''
  description: ''
  version: 1.0.0
paths:
  /v3/app/worksheets:
    post:
      summary: 新建工作表
      deprecated: false
      description: 创建工作表，目前支持字段类型有Text|Number|SingleSelect|MultipleSelect|Date|DateTime|Collaborator|Relation|Attachment
      tags:
      - V3-beta（AI 友好）/工作表
      - 工作表
      parameters:
      - name: HAP-Appkey
        in: header
        description: appkey
        required: false
        schema:
          type: string
      - name: HAP-Sign
        in: header
        description: 签名
        required: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  title: ''
                  description: 工作表名称
                alias:
                  type: string
                  description: 工作表别名
                sectionId:
                  type: string
                  title: ''
                  description: 分组 id
                fields:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        title: ''
                        description: 字段名称
                      alias:
                        type: string
                        title: ''
                        description: 字段别名
                      type:
                        type: string
                        description: 字段类型
                      isTitle:
                        type: boolean
                        description: 是否是标题字段
                      required:
                        type: boolean
                        description: 是否必填
                      isHidden:
                        type: boolean
                        description: 是否隐藏
                      isReadOnly:
                        type: boolean
                        description: 是否只读
                      isHiddenOnCreate:
                        type: boolean
                        description: 是否新增记录时隐藏
                      isUnique:
                        type: boolean
                        description: 是否唯一
                      precision:
                        type: integer
                        description: 'type=Number时，表示保留小数位（0-14）

                          '
                      subType:
                        type: string
                        description: 'type=Collaborator时，表示成员数量，填入规则 0：单选,1：多选

                          type=Relation时，表示关联记录数量，填入规则 1：单条 2：多条

                          type=Time时，表示时间1：时.分 ，6：时.分.秒

                          type=Date|DateTime时，表示日期：5：年 4：年月 3：年月日 2：年月日时 1：年月日时分 6：年月日时分秒'
                      options:
                        type: array
                        items:
                          properties:
                            value:
                              type: string
                              description: 选项名称
                            index:
                              type: integer
                              description: 选项排序
                          required:
                          - value
                          - index
                          $ref: '#/components/schemas/options'
                        description: type=SingleSelect|MultipleSelect时传入， 11:单选,10:多选时填入
                      max:
                        type: integer
                        description: type=Rating时传入，表示等级最大值，填入规则（0-10）
                      dataSource:
                        type: string
                        description: type=Relation时传入关联表 id，表示关联表 id
                      relation:
                        properties:
                          showFields:
                            type: array
                            items:
                              type: string
                            description: 展示字段
                          bidirectional:
                            type: boolean
                            description: 是否为双向关联 true：双向，false：单向
                        description: 'type=Relation时传入，关联字段字段 配置项


                          '
                        $ref: '#/components/schemas/relation'
                    required:
                    - name
                    - type
                    - required
                  title: ''
                  description: 工作表字段信息
              required:
              - name
              - fields
              title: ''
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                properties:
                  data:
                    type: object
                    properties:
                      worksheetId:
                        type: string
                        description: 工作表ID
                    required:
                    - worksheetId
                  success:
                    type: boolean
                    description: 是否调用成功
                  error_code:
                    type: integer
                    description: 错误代码
                  error_msg:
                    type: string
                    description: 错误消息
                required:
                - data
                - success
                title: ''
                type: object
          headers: {}
      security: []
components:
  schemas:
    relation:
      type: object
      properties:
        showFields:
          type: array
          items:
            type: string
          description: 展示字段
        bidirectional:
          type: boolean
          description: 是否为双向关联 true：双向，false：单向
      description: 'type=Relation时传入，关联字段字段 配置项


        '
    options:
      type: object
      properties:
        value:
          type: string
          description: 选项名称
        index:
          type: integer
          description: 选项排序
      required:
      - value
      - index
  securitySchemes:
    bearer:
      type: bearer
      scheme: bearer
servers:
- url: https://api.mingdao.com
  description: 正式环境
security:
- bearer: []
