openapi: 3.0.1
info:
  title: ''
  description: ''
  version: 1.0.0
paths:
  /v3/app/worksheets/{worksheet_id}/rows/{row_id}:
    delete:
      summary: 删除行记录
      deprecated: false
      description: 删除行记录
      tags:
      - V3-beta（AI 友好）/工作表行记录
      - 工作表行记录
      parameters:
      - name: worksheet_id
        in: path
        description: 工作表 ID
        required: true
        schema:
          type: string
      - name: row_id
        in: path
        description: 行记录 ID
        required: true
        schema:
          type: string
      - name: HAP-Appkey
        in: header
        description: appkey
        required: false
        schema:
          type: string
      - name: HAP-Sign
        in: header
        description: 签名
        required: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                triggerWorkflow:
                  type: boolean
                  default: true
                  description: 是否触发工作流
                permanent:
                  type: boolean
                  description: 是否彻底删除 (true：彻底删除，false：逻辑删除，默认为false)，彻底删除后数据不进入回收站，且不可恢复，请谨慎操作！
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties: {}
                  success:
                    type: boolean
                    description: 是否调用成功
                  error_code:
                    type: integer
                    description: 错误代码
                  error_msg:
                    type: string
                    description: 错误消息
                required:
                - data
                - success
          headers: {}
      security: []
components:
  schemas: {}
  securitySchemes:
    bearer:
      type: bearer
      scheme: bearer
servers:
- url: https://api.mingdao.com
  description: 正式环境
security:
- bearer: []
