openapi: 3.0.1
info:
  title: ''
  description: ''
  version: 1.0.0
paths:
  /v3/app/workflow/processes:
    get:
      summary: 获取流程列表
      deprecated: false
      description: 获取应用下工作流列表
      tags:
      - V3-beta（AI 友好）/工作流
      - 工作流
      parameters:
      - name: HAP-Appkey
        in: header
        description: appkey
        required: false
        schema:
          type: string
      - name: HAP-Sign
        in: header
        description: 签名
        required: false
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      processes:
                        type: array
                        items:
                          $ref: '#/components/schemas/obj_process'
                    required:
                    - processes
                  success:
                    type: boolean
                    description: 是否调用成功
                  error_code:
                    type: integer
                    description: 错误代码
                  error_msg:
                    type: string
                    description: 错误消息
                required:
                - data
                - success
          headers: {}
      security: []
components:
  schemas:
    obj_process:
      type: object
      properties:
        id:
          type: string
          description: 流程 id
        name:
          type: string
          description: 流程名称
        type:
          type: integer
          description: 流程类型，6:webhook，10:pbp
        description:
          type: string
          description: 流程描述
        _createdAt:
          type: string
          description: 创建时间
        _updatedAt:
          type: string
          description: 更新时间
        _owner:
          $ref: '#/components/schemas/obj_user'
          description: 拥有者信息
      required:
      - id
      - name
      - description
      - _createdAt
      - _updatedAt
      - _owner
      - type
    obj_user:
      type: object
      properties:
        accountId:
          type: string
          description: 人员 id
        fullname:
          type: string
          description: ' 名称'
        avatar:
          type: string
          description: 头像地址
      required:
      - accountId
      - fullname
      - avatar
  securitySchemes:
    bearer:
      type: bearer
      scheme: bearer
servers:
- url: https://api.mingdao.com
  description: 正式环境
security:
- bearer: []
