openapi: 3.0.1
info:
  title: ''
  description: ''
  version: 1.0.0
paths:
  /v3/app:
    get:
      summary: 获取应用信息
      deprecated: false
      description: 获取应用信息，包含应用下分组、工作表、自定义页面信息
      tags:
      - V3-beta（AI 友好）/应用
      - 应用
      parameters:
      - name: HAP-Appkey
        in: header
        description: appkey
        required: false
        schema:
          type: string
      - name: HAP-Sign
        in: header
        description: 签名
        required: false
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      organizationId:
                        type: string
                        description: 组织 ID
                      appId:
                        type: string
                        description: 应用ID
                      name:
                        type: string
                        description: 应用名称
                      iconUrl:
                        type: string
                        description: 图标地址
                      color:
                        type: string
                        description: 颜色
                      desc:
                        type: string
                        description: 应用说明
                      remark:
                        type: string
                        description: ' 应用描述'
                      sections:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: string
                              description: 应用分组id
                            name:
                              type: string
                              description: 分组名称
                            items:
                              type: array
                              items:
                                properties:
                                  id:
                                    type: string
                                    description: 应用项id
                                  name:
                                    type: string
                                    description: 应用项id
                                  type:
                                    type: integer
                                    description: 应用项类型 0:工作表、1:自定义页面、2：子分组
                                  iconUrl:
                                    type: string
                                    description: 应用项图标地址
                                  status:
                                    type: integer
                                    description: 状态
                                  alias:
                                    type: string
                                    description: 别名
                                  notes:
                                    type: string
                                    description: 开发者备注
                                description: 分组下应用项信息
                                $ref: '#/components/schemas/obj_app'
                              description: 分组下应用项信息
                            childSections:
                              type: array
                              items:
                                type: object
                                properties:
                                  id:
                                    type: string
                                    description: 子分组id
                                  name:
                                    type: string
                                    description: 子分组名称
                                  items:
                                    type: array
                                    items:
                                      properties:
                                        id:
                                          type: string
                                          description: 应用项id
                                        name:
                                          type: string
                                          description: 应用项id
                                        type:
                                          type: integer
                                          description: 应用项类型 0:工作表、1:自定义页面、2：子分组
                                        iconUrl:
                                          type: string
                                          description: 应用项图标地址
                                        status:
                                          type: integer
                                          description: 状态
                                        alias:
                                          type: string
                                          description: 别名
                                        notes:
                                          type: string
                                          description: 开发者备注
                                      description: 分组下应用项信息
                                      $ref: '#/components/schemas/obj_app'
                                required:
                                - id
                                - items
                                - name
                                description: 子分组下应用项信息
                                nullable: true
                              description: 子分组信息
                        description: 分组信息
                    required:
                    - organizationId
                    - appId
                    - name
                    - iconUrl
                    - color
                    - desc
                    - sections
                    - remark
                    description: 返回数据
                  success:
                    type: boolean
                    description: 是否调用成功
                  error_code:
                    type: integer
                    description: 错误代码
                  error_msg:
                    type: string
                    description: 错误消息
                required:
                - data
                - success
          headers: {}
      security: []
components:
  schemas:
    obj_app:
      type: object
      properties:
        id:
          type: string
          description: 应用项id
        name:
          type: string
          description: 应用项名称
        type:
          type: integer
          description: 应用项类型 0:工作表、1:自定义页面、2：子分组
        iconUrl:
          type: string
          description: 应用项图标地址
        status:
          type: integer
          description: 状态
        alias:
          type: string
          description: 别名
        notes:
          type: string
          description: 开发者备注
      description: 分组下应用项信息
  securitySchemes:
    bearer:
      type: bearer
      scheme: bearer
servers:
- url: https://api.mingdao.com
  description: 正式环境
security:
- bearer: []
