openapi: 3.0.1
info:
  title: ''
  description: ''
  version: 1.0.0
paths:
  /v3/regions:
    get:
      summary: 获取地区信息
      deprecated: false
      description: '获取地区信息

        '
      tags:
      - V3-beta（AI 友好）/公共查询
      - 公共查询
      parameters:
      - name: id
        in: query
        description: 地区ID
        required: false
        schema:
          type: string
      - name: search
        in: query
        description: 模糊搜索内容
        required: false
        schema:
          type: string
      - name: HAP-Appkey
        in: header
        description: appkey
        required: false
        schema:
          type: string
      - name: HAP-Sign
        in: header
        description: 签名
        required: false
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      regions:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: string
                              description: 地区ID
                            name:
                              type: string
                              description: 省、市、区/县名称
                            path:
                              type: string
                              description: 地区路径
                            last:
                              type: boolean
                              description: 是否还有下级地区
                        description: 地区列表
                  success:
                    type: boolean
                    description: 是否调用成功
                  error_code:
                    type: integer
                    description: 错误代码
                  error_msg:
                    type: string
                    description: 错误消息
                required:
                - data
                - success
          headers: {}
      security: []
components:
  schemas: {}
  securitySchemes:
    bearer:
      type: bearer
      scheme: bearer
servers:
- url: https://api.mingdao.com
  description: 正式环境
security:
- bearer: []
