openapi: 3.0.1
info:
  title: ''
  description: ''
  version: 1.0.0
paths:
  /v3/app/worksheets/{worksheet_id}/rows/{row_id}/logs:
    get:
      summary: 获取行记录日志
      deprecated: false
      description: 获取行记录日志
      tags:
      - V3-beta（AI 友好）/工作表行记录
      - 工作表行记录
      parameters:
      - name: worksheet_id
        in: path
        description: 工作表 ID
        required: true
        schema:
          type: string
      - name: row_id
        in: path
        description: ' 行记录 ID'
        required: true
        schema:
          type: string
      - name: operatorIds
        in: query
        description: 操作者 id
        required: false
        schema:
          type: array
          items:
            type: string
      - name: field
        in: query
        description: 字段 id/别名
        required: false
        schema:
          type: string
      - name: pageSize
        in: query
        description: ''
        required: false
        schema:
          type: string
      - name: pageIndex
        in: query
        description: ''
        required: false
        schema:
          type: string
      - name: startDate
        in: query
        description: 开始日期，格式：yyyy-MM-dd HH:mm:ss
        required: false
        schema:
          type: string
      - name: endDate
        in: query
        description: '结束日期，yyyy-MM-dd HH:mm:ss

          '
        required: false
        schema:
          type: string
      - name: HAP-Appkey
        in: header
        description: appkey
        required: false
        schema:
          type: string
      - name: HAP-Sign
        in: header
        description: 签名
        required: false
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      logs:
                        $ref: '#/components/schemas/obj_record_log'
                    required:
                    - logs
                  success:
                    type: boolean
                    description: 是否调用成功
                  error_code:
                    type: integer
                    description: 错误代码
                  error_msg:
                    type: string
                    description: 错误消息
                required:
                - data
                - success
          headers: {}
      security: []
components:
  schemas:
    obj_record_log:
      type: object
      properties:
        operator:
          type: object
          properties:
            accountId:
              type: string
              description: 人员 id
            fullname:
              type: string
              description: ' 名称'
            avatar:
              type: string
              description: 头像地址
            isPortal:
              type: boolean
            status:
              type: integer
          required:
          - accountId
          - fullname
          - avatar
          - isPortal
          - status
          description: 操作者信息
          title: 操作者 id
        content:
          type: object
          properties:
            worksheetId:
              type: string
              description: 工作表ID
            objectId:
              type: string
              description: 操作对象ID
            uniqueId:
              type: string
              description: 操作唯一标识
            objectType:
              type: string
              description: 日志对象类型 1:工作表 2:行记录 3:视图 4:按钮 5:业务规则 99:其他
            type:
              type: integer
              description: 日志操作类型 1:手动 2:工作流 3:按钮
            requestType:
              type: string
              description: （待研发补充枚举值）
            _createdAt:
              type: string
              description: 创建时间
            logData:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                    description: 字段 id
                  name:
                    type: string
                    description: 字段名称
                  editType:
                    type: integer
                    description: （待研发补充枚举值）
                  type:
                    type: integer
                    description: 字段类型
                  oldValue:
                    type: string
                    description: 操作前的值
                  oldText:
                    type: string
                    description: 操作前的描述
                  newValue:
                    type: string
                    description: 操作后的值
                  newText:
                    type: string
                    description: 操作后的描述
                  isDeleted:
                    type: boolean
                    description: 是否删除
                description: 日志日期
              description: 操作创建的时间戳
          required:
          - worksheetId
          - objectId
          - uniqueId
          - objectType
          - type
          - requestType
          - _createdAt
          - logData
          description: 操作内容
  securitySchemes:
    bearer:
      type: bearer
      scheme: bearer
servers:
- url: https://api.mingdao.com
  description: 正式环境
security:
- bearer: []
