openapi: 3.0.1
info:
  title: ''
  description: ''
  version: 1.0.0
paths:
  /v3/app/worksheets/{worksheet_id}/rows/{row_id}/discussions:
    get:
      summary: 获取行记录讨论
      deprecated: false
      description: 获取行记录讨论
      tags:
      - V3-beta（AI 友好）/工作表行记录
      - 工作表行记录
      parameters:
      - name: worksheet_id
        in: path
        description: 工作表 ID
        required: true
        schema:
          type: string
      - name: row_id
        in: path
        description: ' 行记录 ID'
        required: true
        schema:
          type: string
      - name: pageIndex
        in: query
        description: ''
        required: false
        schema:
          type: integer
      - name: pageSize
        in: query
        description: ''
        required: false
        schema:
          type: integer
      - name: search
        in: query
        description: ''
        required: false
        schema:
          type: string
      - name: onlyWithAttachments
        in: query
        description: 是否只返回包含附件的讨论
        required: false
        schema:
          type: boolean
          default: false
      - name: HAP-Appkey
        in: header
        description: appkey
        required: false
        schema:
          type: string
      - name: HAP-Sign
        in: header
        description: 签名
        required: false
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      discussions:
                        type: array
                        items:
                          $ref: '#/components/schemas/obj_record_discussion'
                    required:
                    - discussions
                  success:
                    type: boolean
                    description: 是否调用成功
                  error_code:
                    type: integer
                    description: 错误代码
                  error_msg:
                    type: string
                    description: 错误消息
                required:
                - data
                - success
          headers: {}
      security: []
components:
  schemas:
    obj_record_discussion:
      type: object
      properties:
        id:
          type: string
          description: 讨论 id
        message:
          type: string
          description: 讨论内容
        _createdAt:
          type: string
          description: 创建时间
        _createdBy:
          description: 创建人信息
          $ref: '#/components/schemas/obj_user'
        replyToAuthor:
          description: 创建人信息
          $ref: '#/components/schemas/obj_user'
        replyToId:
          type: string
          description: 被回复的讨论 id
        mentions:
          type: array
          items:
            type: object
            properties:
              accountId:
                type: string
                description: 人员 id
              fullname:
                type: string
                description: ' 名称'
              avatar:
                type: string
                description: 头像地址
            required:
            - accountId
            - fullname
            - avatar
        attachments:
          type: array
          items:
            type: object
            properties:
              originalFilename:
                type: string
                description: 文件名称
              ext:
                type: string
                description: 文件类型
              filesize:
                type: string
                description: 文件大小
              downloadUrl:
                type: string
                description: 下载地址
            required:
            - ext
            - filesize
            - downloadUrl
          description: 附件信息
      required:
      - id
      - message
      - _createdAt
      - _createdBy
      - replyToAuthor
      - replyToId
      - mentions
      - attachments
    obj_user:
      type: object
      properties:
        accountId:
          type: string
          description: 人员 id
        fullname:
          type: string
          description: ' 名称'
        avatar:
          type: string
          description: 头像地址
      required:
      - accountId
      - fullname
      - avatar
  securitySchemes:
    bearer:
      type: bearer
      scheme: bearer
servers:
- url: https://api.mingdao.com
  description: 正式环境
security:
- bearer: []
