openapi: 3.0.1
info:
  title: ''
  description: ''
  version: 1.0.0
paths:
  /v3/app/worksheets/{worksheet_id}/rows/{row_id}/share-link:
    post:
      summary: 获取记录分享链接
      deprecated: false
      description: 获取记录分享链接
      tags:
      - V3-beta（AI 友好）/工作表行记录
      - 工作表行记录
      parameters:
      - name: worksheet_id
        in: path
        description: 工作表 ID
        required: true
        schema:
          type: string
      - name: row_id
        in: path
        description: ' 行记录 ID'
        required: true
        schema:
          type: string
      - name: HAP-Appkey
        in: header
        description: appkey
        required: false
        schema:
          type: string
      - name: HAP-Sign
        in: header
        description: 签名
        required: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                visibleFields:
                  type: array
                  items:
                    type: string
                  title: 可见字段ID集合
                expiredIn:
                  type: integer
                  title: 单位s,不传或传0表示永久有效
                password:
                  type: string
                  title: 为空表示不需要密码
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      url:
                        type: string
                        description: 分享链接地址
                    required:
                    - url
                  success:
                    type: boolean
                    description: 是否调用成功
                  error_code:
                    type: integer
                    description: 错误代码
                  error_msg:
                    type: string
                    description: 错误消息
                required:
                - data
                - success
          headers: {}
      security: []
components:
  schemas: {}
  securitySchemes:
    bearer:
      type: bearer
      scheme: bearer
servers:
- url: https://api.mingdao.com
  description: 正式环境
security:
- bearer: []
