openapi: 3.0.1
info:
  title: ''
  description: ''
  version: 1.0.0
paths:
  /v3/app/workflow/processes/{process_id}:
    get:
      summary: 获取流程详情
      deprecated: false
      description: 获取流程详情，包含流程请求参数，响应参数
      tags:
      - V3-beta（AI 友好）/工作流
      - 工作流
      parameters:
      - name: process_id
        in: path
        description: ''
        required: true
        schema:
          type: string
      - name: HAP-Appkey
        in: header
        description: appkey
        required: false
        schema:
          type: string
      - name: HAP-Sign
        in: header
        description: 签名
        required: false
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/obj_process_detail'
                  success:
                    type: boolean
                    description: 是否调用成功
                  error_code:
                    type: integer
                    description: 错误代码
                  error_msg:
                    type: string
                    description: 错误消息
                required:
                - data
                - success
          headers: {}
      security: []
components:
  schemas:
    obj_process_detail:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        inputParameters:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: 字段id
              name:
                type: string
                description: 字段名称
              alias:
                type: string
                description: 别名
              type:
                type: integer
                description: 字段类型
              description:
                type: string
                description: 描述
              required:
                type: boolean
                description: 是否必填
              options:
                type: array
                items:
                  type: object
                  properties:
                    key:
                      type: string
                    value:
                      type: string
                  required:
                  - key
                  - value
                description: 选项集,字段类型为选项时，返回选项名称数组
              items:
                type: array
                items:
                  $ref: '#/components/schemas/obj_input'
                description: 如果参数是对象数组，这是对象数组的子字段结构
            required:
            - id
            - name
            - alias
            - type
            - description
            - required
        outputParameters:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: 字段id
              name:
                type: string
                description: 字段名称
              type:
                type: integer
                description: 字段类型
              description:
                type: string
                description: 描述
              items:
                type: array
                items:
                  $ref: '#/components/schemas/obj_output'
                description: 如果参数是对象数组，这是子字段结构
            required:
            - id
            - name
            - type
            - description
      required:
      - inputParameters
      - outputParameters
    obj_output:
      type: object
      properties:
        id:
          type: string
          description: 字段id
        name:
          type: string
          description: 字段名称
        type:
          type: integer
          description: 字段类型
        description:
          type: string
          description: 描述
      required:
      - id
      - name
      - type
      - description
    obj_input:
      type: object
      properties:
        id:
          type: string
          description: 字段id
        name:
          type: string
          description: 字段名称
        alias:
          type: string
          description: 别名
        type:
          type: integer
          description: 字段类型
        description:
          type: string
          description: 描述
        required:
          type: boolean
          description: 是否必填
        options:
          type: array
          items:
            type: object
            properties:
              key:
                type: string
              value:
                type: string
            required:
            - key
            - value
          description: 选项集,字段类型为选项时，返回选项名称数组
      required:
      - id
      - name
      - alias
      - type
      - description
      - required
  securitySchemes:
    bearer:
      type: bearer
      scheme: bearer
servers:
- url: https://api.mingdao.com
  description: 正式环境
security:
- bearer: []
