openapi: 3.0.1
info:
  title: ''
  description: ''
  version: 1.0.0
paths:
  /v3/app/workflow/hooks/{process_id}:
    post:
      summary: 触发流程
      deprecated: false
      description: 触发流程
      tags:
      - V3-beta（AI 友好）/工作流
      - 工作流
      parameters:
      - name: process_id
        in: path
        description: ''
        required: true
        schema:
          type: string
      - name: HAP-Appkey
        in: header
        description: appkey
        required: false
        schema:
          type: string
      - name: HAP-Sign
        in: header
        description: 签名
        required: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                '{inputs}':
                  description: '流程的输入参数及对应的值

                    '
                  oneOf:
                  - type: string
                  - type: integer
                  - type: boolean
                  - type: array
                  - type: object
                  - type: number
                  type: 'null'
              required:
              - '{inputs}'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  '{outputs}':
                    oneOf:
                    - type: string
                    - type: integer
                    - type: boolean
                    - type: array
                    - type: object
                    - type: number
                    type: 'null'
                required:
                - '{outputs}'
          headers: {}
      security: []
components:
  schemas: {}
  securitySchemes:
    bearer:
      type: bearer
      scheme: bearer
servers:
- url: https://api.mingdao.com
  description: 正式环境
security:
- bearer: []
